name: api automation

on:
  workflow_dispatch

jobs:
  api-automation:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install locust
        run: make install-locust

      - name: run api-automation
        run: make run-api-automation
      
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: path.html
